{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# JSL Raigarh — Hourly Air Quality Analysis\n",
    "**Jindal Steel Limited | 5 Monitoring Locations | 7 Parameters + CPCB AQI**\n",
    "\n",
    "This notebook:\n",
    "1. Renders each PDF page as a high-resolution image (works with image-based PDFs)\n",
    "2. Sends pages to Claude Vision API for accurate date-time + data extraction\n",
    "3. Calculates CPCB AQI sub-indices per hour per location\n",
    "4. Produces a single scrollable dashboard figure saved as PNG\n",
    "\n",
    "---\n",
    "### Requirements\n",
    "```\n",
    "pip install anthropic pymupdf pandas matplotlib pillow\n",
    "```"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 1 · Install dependencies ─────────────────────────────────────────────\n",
    "import subprocess, sys\n",
    "packages = ['anthropic', 'pymupdf', 'pandas', 'matplotlib', 'pillow']\n",
    "for pkg in packages:\n",
    "    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '--quiet', pkg])\n",
    "print('✓ All packages ready')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 2 · Imports & configuration ──────────────────────────────────────────\n",
    "import os, json, base64, re, pickle, warnings\n",
    "from pathlib import Path\n",
    "from io import BytesIO\n",
    "\n",
    "import fitz                          # PyMuPDF\n",
    "import anthropic\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as mpatches\n",
    "import matplotlib.lines as mlines\n",
    "from matplotlib.gridspec import GridSpec\n",
    "from PIL import Image\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "matplotlib.rcParams.update({\n",
    "    'figure.dpi': 120,\n",
    "    'font.family': 'DejaVu Sans',\n",
    "    'axes.spines.top': False,\n",
    "    'axes.spines.right': False,\n",
    "    'axes.grid': True,\n",
    "    'grid.alpha': 0.35,\n",
    "    'grid.linestyle': '--',\n",
    "})\n",
    "\n",
    "# ── USER SETTINGS ─────────────────────────────────────────────────────────────\n",
    "PDF_PATHS = [\n",
    "    r\"138102.pdf\",           # ← put your PDF path(s) here; add more for multi-day\n",
    "]\n",
    "API_KEY   = os.environ.get('ANTHROPIC_API_KEY', 'YOUR_API_KEY_HERE')\n",
    "CACHE_DIR = Path('aqi_cache')        # extracted JSON is cached here to avoid re-calling API\n",
    "OUT_PNG   = Path('JSL_AQI_dashboard.png')\n",
    "RENDER_DPI = 200                     # higher = clearer OCR, slower render\n",
    "\n",
    "CACHE_DIR.mkdir(exist_ok=True)\n",
    "print('✓ Configuration loaded')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 3 · PDF → page images ────────────────────────────────────────────────\n",
    "def pdf_to_images(pdf_path: str, dpi: int = 200) -> list[str]:\n",
    "    \"\"\"\n",
    "    Render every page of an image-based PDF to a JPEG base64 string.\n",
    "    Returns list of base64 strings, one per page.\n",
    "    \"\"\"\n",
    "    doc = fitz.open(pdf_path)\n",
    "    mat = fitz.Matrix(dpi / 72, dpi / 72)   # 72 dpi is PDF default\n",
    "    images = []\n",
    "    for page_num in range(len(doc)):\n",
    "        page = doc[page_num]\n",
    "        pix  = page.get_pixmap(matrix=mat, colorspace=fitz.csRGB, alpha=False)\n",
    "        img  = Image.frombytes('RGB', [pix.width, pix.height], pix.samples)\n",
    "        buf  = BytesIO()\n",
    "        img.save(buf, format='JPEG', quality=90)\n",
    "        b64  = base64.b64encode(buf.getvalue()).decode()\n",
    "        images.append(b64)\n",
    "        print(f'  Page {page_num+1}/{len(doc)} rendered ({pix.width}×{pix.height}px)')\n",
    "    doc.close()\n",
    "    return images\n",
    "\n",
    "print('✓ pdf_to_images() defined')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 4 · Claude Vision extraction ─────────────────────────────────────────\n",
    "EXTRACTION_PROMPT = \"\"\"\\\n",
    "These are pages from a Jindal Steel Limited Raigarh daily air quality monitoring report.\n",
    "Each page contains one table for one monitoring location with 24 hourly rows.\n",
    "\n",
    "The first column is a merged \"Date - Time\" column that looks like: 2026-04-12 00\n",
    "(YYYY-MM-DD followed by the 2-digit hour 00–23 on the same or next sub-row).\n",
    "Read both the date AND the hour carefully — they may be visually stacked or space-separated.\n",
    "\n",
    "Columns in order: Date-Time, CO (mg/m³), NO2 (µg/m³), SO2 (µg/m³),\n",
    "PM10 (µg/m³), PM2.5 (µg/m³), O3 (µg/m³), NH3 (µg/m³).\n",
    "\n",
    "Location names appear in the table header and match one of:\n",
    "  East STP-II | West STP-II | North E&F Colony | South Shramik Vihar | Cement Plant\n",
    "\n",
    "Return ONLY valid JSON — no markdown fences, no explanation:\n",
    "{\n",
    "  \"date\": \"YYYY-MM-DD\",\n",
    "  \"locations\": {\n",
    "    \"East STP-II\": {\n",
    "      \"hours\": [\n",
    "        {\"hour\": 0, \"CO\": 1.02, \"NO2\": 17.6, \"SO2\": 8.8, \"PM10\": 6, \"PM2_5\": 9, \"O3\": 28.6, \"NH3\": 5.7},\n",
    "        ... (all 24 hours)\n",
    "      ]\n",
    "    },\n",
    "    \"West STP-II\": { \"hours\": [...] },\n",
    "    \"North E&F Colony\": { \"hours\": [...] },\n",
    "    \"South Shramik Vihar\": { \"hours\": [...] },\n",
    "    \"Cement Plant\": { \"hours\": [...] }\n",
    "  }\n",
    "}\n",
    "\n",
    "Rules:\n",
    "- Exactly 24 entries per location (hour 0–23). Use null for genuinely missing values.\n",
    "- Highlighted (yellow) cells still get their numeric value extracted normally.\n",
    "- Skip MIN / MAX / AVG summary rows entirely.\n",
    "- Extract only locations visible in this batch of pages.\n",
    "\"\"\"\n",
    "\n",
    "def extract_with_claude(images: list[str], api_key: str) -> dict:\n",
    "    \"\"\"\n",
    "    Send page images to Claude claude-sonnet-4-20250514 and return parsed JSON.\n",
    "    \"\"\"\n",
    "    client  = anthropic.Anthropic(api_key=api_key)\n",
    "    content = []\n",
    "    for i, b64 in enumerate(images):\n",
    "        content.append({\n",
    "            'type': 'image',\n",
    "            'source': {'type': 'base64', 'media_type': 'image/jpeg', 'data': b64}\n",
    "        })\n",
    "        content.append({'type': 'text', 'text': f'Page {i+1} of {len(images)}'})\n",
    "    content.append({'type': 'text', 'text': EXTRACTION_PROMPT})\n",
    "\n",
    "    msg = client.messages.create(\n",
    "        model      = 'claude-sonnet-4-20250514',\n",
    "        max_tokens = 4096,\n",
    "        messages   = [{'role': 'user', 'content': content}]\n",
    "    )\n",
    "    raw = ''.join(b.text for b in msg.content if hasattr(b, 'text'))\n",
    "    raw = re.sub(r'```json\\s*', '', raw).replace('```', '').strip()\n",
    "    return json.loads(raw)\n",
    "\n",
    "print('✓ extract_with_claude() defined')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 5 · Process PDF(s) — uses disk cache to avoid repeat API calls ────────\n",
    "all_data = {}   # date → parsed JSON\n",
    "\n",
    "for pdf_path in PDF_PATHS:\n",
    "    pdf_path  = Path(pdf_path)\n",
    "    cache_key = pdf_path.stem\n",
    "    cache_file = CACHE_DIR / f'{cache_key}.json'\n",
    "\n",
    "    if cache_file.exists():\n",
    "        print(f'📂  Loading cached data for {pdf_path.name}')\n",
    "        with open(cache_file) as f:\n",
    "            data = json.load(f)\n",
    "    else:\n",
    "        print(f'\\n🔍  Processing {pdf_path.name} ...')\n",
    "        print('  Rendering pages ...')\n",
    "        images = pdf_to_images(str(pdf_path), dpi=RENDER_DPI)\n",
    "        print(f'  Sending {len(images)} page(s) to Claude Vision ...')\n",
    "        data   = extract_with_claude(images, API_KEY)\n",
    "        # Sort hours\n",
    "        for loc in data['locations'].values():\n",
    "            loc['hours'].sort(key=lambda h: h['hour'])\n",
    "        with open(cache_file, 'w') as f:\n",
    "            json.dump(data, f, indent=2)\n",
    "        print(f'  ✓ Cached to {cache_file}')\n",
    "\n",
    "    all_data[data['date']] = data\n",
    "    locs = list(data['locations'].keys())\n",
    "    hrs  = sum(len(v['hours']) for v in data['locations'].values())\n",
    "    print(f'  📅  {data[\"date\"]} | {len(locs)} location(s) | {hrs} hourly readings')\n",
    "\n",
    "print('\\n✓ All PDFs processed')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 6 · Build DataFrames + compute CPCB AQI ──────────────────────────────\n",
    "\n",
    "# CPCB 24-hr breakpoints (Conc_Low, Conc_High, AQI_Low, AQI_High)\n",
    "AQI_BP = {\n",
    "    'PM2_5': [(0,30,0,50),(31,60,51,100),(61,90,101,200),(91,120,201,300),(121,250,301,400),(251,500,401,500)],\n",
    "    'PM10':  [(0,50,0,50),(51,100,51,100),(101,250,101,200),(251,350,201,300),(351,430,301,400),(431,600,401,500)],\n",
    "    'NO2':   [(0,40,0,50),(41,80,51,100),(81,180,101,200),(181,280,201,300),(281,400,301,400),(401,800,401,500)],\n",
    "    'SO2':   [(0,40,0,50),(41,80,51,100),(81,380,101,200),(381,800,201,300),(801,1600,301,400),(1601,2620,401,500)],\n",
    "    'CO':    [(0,1.0,0,50),(1.1,2.0,51,100),(2.1,10.0,101,200),(10.1,17.0,201,300),(17.1,34.0,301,400),(34.1,50.0,401,500)],\n",
    "    'O3':    [(0,50,0,50),(51,100,51,100),(101,168,101,200),(169,208,201,300),(209,748,301,400),(749,1000,401,500)],\n",
    "    'NH3':   [(0,200,0,50),(201,400,51,100),(401,800,101,200),(801,1200,201,300),(1201,1800,301,400),(1801,3600,401,500)],\n",
    "}\n",
    "CPCB_LIMITS = {'CO':2, 'NO2':80, 'SO2':80, 'PM10':100, 'PM2_5':60, 'O3':100, 'NH3':400}\n",
    "PARAMS      = ['CO','NO2','SO2','PM10','PM2_5','O3','NH3']\n",
    "PARAM_LABELS = {'CO':'CO (mg/m³)','NO2':'NO₂ (µg/m³)','SO2':'SO₂ (µg/m³)',\n",
    "                'PM10':'PM₁₀ (µg/m³)','PM2_5':'PM₂.₅ (µg/m³)',\n",
    "                'O3':'O₃ (µg/m³)','NH3':'NH₃ (µg/m³)'}\n",
    "\n",
    "def sub_index(pol, c):\n",
    "    if c is None or (isinstance(c, float) and np.isnan(c)):\n",
    "        return np.nan\n",
    "    for cL, cH, iL, iH in AQI_BP[pol]:\n",
    "        if cL <= float(c) <= cH:\n",
    "            return round(((iH - iL) / (cH - cL)) * (float(c) - cL) + iL)\n",
    "    return 500 if float(c) > AQI_BP[pol][-1][1] else np.nan\n",
    "\n",
    "def aqi_category(v):\n",
    "    if np.isnan(v):      return ('N/A',      '#999999')\n",
    "    if v <= 50:          return ('Good',      '#009966')\n",
    "    if v <= 100:         return ('Satisfactory','#FFDE33')\n",
    "    if v <= 200:         return ('Moderate',  '#FF9933')\n",
    "    if v <= 300:         return ('Poor',      '#CC0033')\n",
    "    if v <= 400:         return ('Very Poor', '#660099')\n",
    "    return               ('Severe',           '#7E0023')\n",
    "\n",
    "# Build one combined DataFrame across all dates\n",
    "frames = []\n",
    "for date, data in all_data.items():\n",
    "    for loc, locdata in data['locations'].items():\n",
    "        for h in locdata['hours']:\n",
    "            row = {'date': date, 'location': loc, 'hour': h['hour'],\n",
    "                   'datetime': pd.to_datetime(f\"{date} {h['hour']:02d}:00\")}\n",
    "            for p in PARAMS:\n",
    "                row[p] = h.get(p)\n",
    "            frames.append(row)\n",
    "\n",
    "df = pd.DataFrame(frames)\n",
    "for p in PARAMS:\n",
    "    df[p] = pd.to_numeric(df[p], errors='coerce')\n",
    "\n",
    "# Compute AQI sub-indices and overall AQI\n",
    "for p in PARAMS:\n",
    "    df[f'si_{p}'] = df[p].apply(lambda v: sub_index(p, v))\n",
    "df['AQI'] = df[[f'si_{p}' for p in PARAMS]].max(axis=1)\n",
    "df['AQI_cat'], df['AQI_color'] = zip(*df['AQI'].apply(\n",
    "    lambda v: aqi_category(v) if not pd.isna(v) else ('N/A','#999')))\n",
    "\n",
    "LOCATIONS = sorted(df['location'].unique())\n",
    "LOC_COLORS = ['#3266AD','#E24B4A','#1D9E75','#7F77DD','#EF9F27']\n",
    "LOC_CLR = dict(zip(LOCATIONS, LOC_COLORS))\n",
    "\n",
    "print(f'✓ DataFrame built: {len(df)} rows | {len(LOCATIONS)} locations')\n",
    "print(f'  Locations: {LOCATIONS}')\n",
    "print(f'  Dates: {sorted(df[\"date\"].unique())}')\n",
    "df.head(3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 7 · Quick summary stats table ────────────────────────────────────────\n",
    "summary = df.groupby(['date','location']).agg(\n",
    "    AQI_max   = ('AQI',   'max'),\n",
    "    AQI_avg   = ('AQI',   'mean'),\n",
    "    PM10_max  = ('PM10',  'max'),\n",
    "    PM25_max  = ('PM2_5', 'max'),\n",
    "    SO2_max   = ('SO2',   'max'),\n",
    "    NO2_max   = ('NO2',   'max'),\n",
    ").round(1).reset_index()\n",
    "\n",
    "# Count exceedance hours per location per date\n",
    "exc_counts = []\n",
    "for p, lim in CPCB_LIMITS.items():\n",
    "    exc = df[df[p] > lim].groupby(['date','location']).size().rename(f'{p}_exc_hrs')\n",
    "    exc_counts.append(exc)\n",
    "\n",
    "if exc_counts:\n",
    "    exc_df = pd.concat(exc_counts, axis=1).fillna(0).astype(int).reset_index()\n",
    "    summary = summary.merge(exc_df, on=['date','location'], how='left').fillna(0)\n",
    "\n",
    "print('📊  Summary statistics:')\n",
    "summary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 8 · MAIN DASHBOARD FIGURE ────────────────────────────────────────────\n",
    "# Layout: 8 rows (7 params + AQI) × 1 column, very tall figure for scrolling in Jupyter\n",
    "\n",
    "HOURS   = list(range(24))\n",
    "X_TICKS = list(range(0, 24, 2))\n",
    "X_LABS  = [f'{h:02d}:00' for h in X_TICKS]\n",
    "\n",
    "# One figure per date in the data\n",
    "for date in sorted(df['date'].unique()):\n",
    "    dfd = df[df['date'] == date].copy()\n",
    "\n",
    "    fig = plt.figure(figsize=(18, 56), constrained_layout=False)\n",
    "    fig.patch.set_facecolor('#F8F9FA')\n",
    "\n",
    "    # Master title\n",
    "    fig.suptitle(\n",
    "        f'JSL Raigarh — Hourly Air Quality Dashboard\\n{date}',\n",
    "        fontsize=18, fontweight='bold', color='#1A202C', y=0.995\n",
    "    )\n",
    "\n",
    "    gs = GridSpec(9, 1, figure=fig,\n",
    "                  top=0.978, bottom=0.02,\n",
    "                  hspace=0.55)\n",
    "\n",
    "    # ── helper: shade AQI bands as background ──────────────────────────────\n",
    "    AQI_BANDS = [\n",
    "        (0,   50,  '#009966', 'Good'),\n",
    "        (50,  100, '#FFDE33', 'Satisfactory'),\n",
    "        (100, 200, '#FF9933', 'Moderate'),\n",
    "        (200, 300, '#CC0033', 'Poor'),\n",
    "        (300, 400, '#660099', 'Very Poor'),\n",
    "        (400, 500, '#7E0023', 'Severe'),\n",
    "    ]\n",
    "\n",
    "    def shade_aqi_bands(ax):\n",
    "        for lo, hi, col, lbl in AQI_BANDS:\n",
    "            ax.axhspan(lo, hi, alpha=0.07, color=col, zorder=0)\n",
    "\n",
    "    def style_ax(ax, ylabel, limit=None, show_limit_label=True):\n",
    "        ax.set_xlim(-0.5, 23.5)\n",
    "        ax.set_xticks(X_TICKS)\n",
    "        ax.set_xticklabels(X_LABS, fontsize=8, rotation=30, ha='right')\n",
    "        ax.set_ylabel(ylabel, fontsize=9, labelpad=6, color='#4A5568')\n",
    "        ax.tick_params(axis='y', labelsize=8)\n",
    "        ax.set_facecolor('#FFFFFF')\n",
    "        for spine in ax.spines.values():\n",
    "            spine.set_edgecolor('#E2E8F0')\n",
    "        if limit is not None:\n",
    "            ax.axhline(limit, color='#E53E3E', linewidth=1.4,\n",
    "                       linestyle='--', zorder=4,\n",
    "                       label=f'CPCB limit ({limit})' if show_limit_label else None)\n",
    "\n",
    "    # ── Plot each parameter ────────────────────────────────────────────────\n",
    "    for idx, param in enumerate(PARAMS):\n",
    "        ax = fig.add_subplot(gs[idx])\n",
    "        style_ax(ax, PARAM_LABELS[param], limit=CPCB_LIMITS.get(param))\n",
    "\n",
    "        any_exceedance = False\n",
    "        for loc in LOCATIONS:\n",
    "            sub  = dfd[dfd['location'] == loc].sort_values('hour')\n",
    "            vals = [sub[sub['hour'] == h][param].values[0]\n",
    "                    if not sub[sub['hour'] == h].empty else np.nan for h in HOURS]\n",
    "            lim  = CPCB_LIMITS.get(param)\n",
    "\n",
    "            # Draw line\n",
    "            ax.plot(HOURS, vals, color=LOC_CLR[loc], linewidth=1.8,\n",
    "                    marker='o', markersize=3.5, zorder=3, label=loc)\n",
    "\n",
    "            # Shade area under curve\n",
    "            ax.fill_between(HOURS, vals, alpha=0.07,\n",
    "                            color=LOC_CLR[loc], zorder=2)\n",
    "\n",
    "            # Mark exceedance points with larger red marker\n",
    "            if lim:\n",
    "                exc_h = [h for h, v in zip(HOURS, vals)\n",
    "                         if v is not None and not np.isnan(v) and v > lim]\n",
    "                exc_v = [vals[h] for h in exc_h]\n",
    "                if exc_h:\n",
    "                    ax.scatter(exc_h, exc_v, color='#E53E3E', s=55,\n",
    "                               zorder=5, marker='^', edgecolors='white', linewidth=0.6)\n",
    "                    any_exceedance = True\n",
    "\n",
    "        # Exceedance badge\n",
    "        if any_exceedance and CPCB_LIMITS.get(param):\n",
    "            ax.text(0.99, 0.96, '⚠ Exceedance', transform=ax.transAxes,\n",
    "                    ha='right', va='top', fontsize=7.5, color='#C53030',\n",
    "                    fontweight='bold',\n",
    "                    bbox=dict(boxstyle='round,pad=0.3', facecolor='#FFF5F5',\n",
    "                              edgecolor='#FC8181', linewidth=0.8))\n",
    "\n",
    "        ax.set_title(PARAM_LABELS[param], fontsize=10, fontweight='600',\n",
    "                     color='#2D3748', pad=4, loc='left')\n",
    "\n",
    "        # Legend inside each subplot (small)\n",
    "        handles = [mlines.Line2D([],[],color=LOC_CLR[l],linewidth=1.5,label=l) for l in LOCATIONS]\n",
    "        if CPCB_LIMITS.get(param):\n",
    "            handles.append(mlines.Line2D([],[],color='#E53E3E',linewidth=1.5,\n",
    "                           linestyle='--',label=f'CPCB limit ({CPCB_LIMITS[param]})'))\n",
    "            handles.append(mlines.Line2D([],[],color='#E53E3E',linewidth=0,\n",
    "                           marker='^',markersize=5,label='Exceedance hour'))\n",
    "        ax.legend(handles=handles, loc='upper right', fontsize=7,\n",
    "                  framealpha=0.85, edgecolor='#E2E8F0', ncol=2)\n",
    "\n",
    "    # ── AQI subplot (bottom) ──────────────────────────────────────────────\n",
    "    ax_aqi = fig.add_subplot(gs[7])\n",
    "    style_ax(ax_aqi, 'CPCB AQI index')\n",
    "    shade_aqi_bands(ax_aqi)\n",
    "\n",
    "    for loc in LOCATIONS:\n",
    "        sub  = dfd[dfd['location'] == loc].sort_values('hour')\n",
    "        vals = [sub[sub['hour'] == h]['AQI'].values[0]\n",
    "                if not sub[sub['hour'] == h].empty else np.nan for h in HOURS]\n",
    "        ax_aqi.plot(HOURS, vals, color=LOC_CLR[loc], linewidth=2,\n",
    "                    marker='o', markersize=3.5, zorder=3, label=loc)\n",
    "        ax_aqi.fill_between(HOURS, vals, alpha=0.07, color=LOC_CLR[loc], zorder=2)\n",
    "\n",
    "    # AQI category band labels\n",
    "    for lo, hi, col, lbl in AQI_BANDS:\n",
    "        mid = (lo + hi) / 2\n",
    "        ax_aqi.text(-0.35, mid, lbl, fontsize=6.5, color=col,\n",
    "                    va='center', fontweight='bold', alpha=0.85)\n",
    "\n",
    "    ax_aqi.set_ylim(0, 520)\n",
    "    ax_aqi.set_title('CPCB AQI (sub-index method — max of all pollutant sub-indices)',\n",
    "                     fontsize=10, fontweight='600', color='#2D3748', pad=4, loc='left')\n",
    "    handles_aqi = [mlines.Line2D([],[],color=LOC_CLR[l],linewidth=1.5,label=l)\n",
    "                   for l in LOCATIONS]\n",
    "    ax_aqi.legend(handles=handles_aqi, loc='upper right', fontsize=7,\n",
    "                  framealpha=0.85, edgecolor='#E2E8F0', ncol=2)\n",
    "\n",
    "    # ── Exceedance summary table (bottom strip) ───────────────────────────\n",
    "    ax_tbl = fig.add_subplot(gs[8])\n",
    "    ax_tbl.axis('off')\n",
    "\n",
    "    col_labels = ['Location'] + [f'{p}\\n(lim {CPCB_LIMITS[p]})' for p in PARAMS] + ['Peak\\nAQI', 'AQI\\nCategory']\n",
    "    table_rows = []\n",
    "    row_colors = []\n",
    "    for loc in LOCATIONS:\n",
    "        sub  = dfd[dfd['location'] == loc]\n",
    "        row  = [loc]\n",
    "        rclr = ['#FFFFFF']\n",
    "        for p in PARAMS:\n",
    "            lim  = CPCB_LIMITS[p]\n",
    "            mx   = sub[p].max()\n",
    "            exc  = int((sub[p] > lim).sum())\n",
    "            cell = f'{mx:.1f}\\n({exc}h ⚠)' if exc > 0 else f'{mx:.1f}'\n",
    "            row.append(cell)\n",
    "            rclr.append('#FFF5F5' if exc > 0 else '#F0FFF4')\n",
    "        peak_aqi = sub['AQI'].max()\n",
    "        cat, col = aqi_category(peak_aqi)\n",
    "        row.append(f'{peak_aqi:.0f}')\n",
    "        row.append(cat)\n",
    "        rclr += ['#FFFFF0', '#F7FAFC']\n",
    "        table_rows.append(row)\n",
    "        row_colors.append(rclr)\n",
    "\n",
    "    tbl = ax_tbl.table(\n",
    "        cellText    = table_rows,\n",
    "        colLabels   = col_labels,\n",
    "        cellColours = row_colors,\n",
    "        cellLoc     = 'center',\n",
    "        loc         = 'center'\n",
    "    )\n",
    "    tbl.auto_set_font_size(False)\n",
    "    tbl.set_fontsize(8)\n",
    "    tbl.scale(1, 2.2)\n",
    "    for (r, c), cell in tbl.get_celld().items():\n",
    "        cell.set_edgecolor('#E2E8F0')\n",
    "        if r == 0:\n",
    "            cell.set_facecolor('#EDF2F7')\n",
    "            cell.set_text_props(fontweight='bold', fontsize=7.5, color='#2D3748')\n",
    "\n",
    "    ax_tbl.set_title('Exceedance summary — max observed vs CPCB limit (exceedance hours in brackets)',\n",
    "                     fontsize=9, fontweight='600', color='#2D3748', pad=6, loc='left')\n",
    "\n",
    "    # ── Save ──────────────────────────────────────────────────────────────\n",
    "    out = Path(str(OUT_PNG).replace('.png', f'_{date}.png'))\n",
    "    fig.savefig(out, dpi=130, bbox_inches='tight',\n",
    "                facecolor=fig.get_facecolor())\n",
    "    print(f'\\n✅  Dashboard saved → {out}')\n",
    "    plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 9 · Multi-day trend view (if multiple PDFs uploaded) ─────────────────\n",
    "if len(all_data) > 1:\n",
    "    print('📈  Generating multi-day trend chart...')\n",
    "    dates_sorted = sorted(df['date'].unique())\n",
    "\n",
    "    fig2, axes = plt.subplots(4, 2, figsize=(18, 22))\n",
    "    fig2.patch.set_facecolor('#F8F9FA')\n",
    "    fig2.suptitle('JSL Raigarh — Multi-day Daily Average Trends',\n",
    "                  fontsize=15, fontweight='bold', y=0.998)\n",
    "    axes_flat = axes.flatten()\n",
    "\n",
    "    for idx, param in enumerate(PARAMS):\n",
    "        ax = axes_flat[idx]\n",
    "        ax.set_facecolor('#FFFFFF')\n",
    "        for loc in LOCATIONS:\n",
    "            daily_avg = df[df['location']==loc].groupby('date')[param].mean()\n",
    "            ax.plot(range(len(dates_sorted)), [daily_avg.get(d, np.nan) for d in dates_sorted],\n",
    "                    color=LOC_CLR[loc], marker='o', linewidth=2, label=loc)\n",
    "        if CPCB_LIMITS.get(param):\n",
    "            ax.axhline(CPCB_LIMITS[param], color='#E53E3E', linewidth=1.2,\n",
    "                       linestyle='--', label=f'CPCB limit')\n",
    "        ax.set_xticks(range(len(dates_sorted)))\n",
    "        ax.set_xticklabels(dates_sorted, rotation=30, fontsize=8)\n",
    "        ax.set_title(PARAM_LABELS[param], fontsize=10, fontweight='600')\n",
    "        ax.legend(fontsize=7, framealpha=0.85)\n",
    "\n",
    "    # AQI panel\n",
    "    ax = axes_flat[7]\n",
    "    ax.set_facecolor('#FFFFFF')\n",
    "    for lo, hi, col, lbl in AQI_BANDS:\n",
    "        ax.axhspan(lo, hi, alpha=0.1, color=col)\n",
    "    for loc in LOCATIONS:\n",
    "        daily_aqi = df[df['location']==loc].groupby('date')['AQI'].mean()\n",
    "        ax.plot(range(len(dates_sorted)), [daily_aqi.get(d, np.nan) for d in dates_sorted],\n",
    "                color=LOC_CLR[loc], marker='o', linewidth=2, label=loc)\n",
    "    ax.set_xticks(range(len(dates_sorted)))\n",
    "    ax.set_xticklabels(dates_sorted, rotation=30, fontsize=8)\n",
    "    ax.set_title('CPCB AQI (daily average)', fontsize=10, fontweight='600')\n",
    "    ax.legend(fontsize=7, framealpha=0.85)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    out2 = Path('JSL_AQI_multiday_trend.png')\n",
    "    fig2.savefig(out2, dpi=130, bbox_inches='tight')\n",
    "    print(f'✅  Multi-day trend saved → {out2}')\n",
    "    plt.show()\n",
    "else:\n",
    "    print('ℹ️   Only one date loaded — upload more PDFs to see multi-day trends.')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "## How to use\n",
    "\n",
    "1. Set your `ANTHROPIC_API_KEY` in Cell 2 (or as an environment variable)\n",
    "2. Set `PDF_PATHS` to a list of your daily report PDFs\n",
    "3. Run all cells — pages are rendered to images automatically (works with image-based PDFs)\n",
    "4. Extracted data is **cached** in `aqi_cache/` so re-running is instant\n",
    "5. To analyse a new day, simply add the new PDF path to `PDF_PATHS` and re-run\n",
    "\n",
    "### Output files\n",
    "| File | Contents |\n",
    "|---|---|\n",
    "| `JSL_AQI_dashboard_YYYY-MM-DD.png` | Full 8-panel scrollable dashboard for that date |\n",
    "| `JSL_AQI_multiday_trend.png` | Daily average trends across all uploaded dates |\n",
    "| `aqi_cache/*.json` | Cached extracted data (delete to force re-extraction) |\n",
    "\n",
    "### What the dashboard shows\n",
    "- **Panels 1–7** — one panel per parameter (CO, NO₂, SO₂, PM₁₀, PM₂.₅, O₃, NH₃) with all 5 locations overlaid, CPCB limit dashed line, and red triangles marking exceedance hours\n",
    "- **Panel 8** — CPCB AQI (max sub-index method) with colour-coded category bands\n",
    "- **Bottom table** — per-location summary: peak value, exceedance hours, peak AQI category"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
